language: node_js
node_js: "8"
jobs:
  include:
    - stage: "Tests & coverage"
      before_install:
        - travis_retry npm install -g codecov
      install:
        - travis_retry npm install
      script:
        - npm run format
        - npm run lint
        - npm run test
        - npm run build
        - npm run doc
        - codecov
    - stage: "Tests & coverage"
      install:
        - npm ci
      cache:
        directories:
          - "$HOME/.npm"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/
  target-branch: gh-pages
  on:
    branch: master
