name: 'Add PR to Project Board - Wallet Framework Team'

on:
  workflow_dispatch:
  pull_request:
    types: [opened, labeled, review_requested]

jobs:
  add-to-project:
    name: Add PR to Project Board
    runs-on: ubuntu-latest
    env:
      TEAM_NAME: 'wallet-framework-engineers'
      TEAM_LABEL: 'team-wallet-framework'

    steps:
      - name: Add PR to project board
        uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e
        if: |
          github.event.requested_team.name == env.TEAM_NAME || 
          contains(github.event.pull_request.labels.*.name, env.TEAM_LABEL)
        with:
          project-url: https://github.com/users/desi/projects/1
          github-token: ${{ secrets.CORE_ADD_PRS_TO_PROJECT }}
