name: 'Add Wallet Framework Issues/PRs to Project Board'

on:
  pull_request:
    types: [opened, labeled, review_requested]
  issues:
    types: [opened, labeled]

jobs:
  call_shared_workflow:
    name: 'Call the Shared Workflow'
    permissions:
      issues: write
      pull-requests: write
      contents: read
      repository-projects: write
    uses: metamask/github-tools/.github/workflows/add-item-to-project.yml@603848896b81e41539ea7688e5481839fde39a7f
    with:
      project-url: 'https://github.com/orgs/MetaMask/projects/113'
      team-name: 'wallet-framework-engineers'
      team-label: 'team-wallet-framework'
    secrets:
      github-token: ${{ secrets.CORE_ADD_PRS_TO_PROJECT }}
